[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "likepep403"
version = "1.0.1"
requires-python = ">=3.9"

[tool.isort]
profile = "black"